### ISSUE TITLE
PIN CE of ESP32

### ISSUE THREAD

**Issue by saadsdz** [Erriez/ErriezDS1302#2]
There issue when we use in the same time an SPI on ESP32 (in our case to communicate with LORA module) and DS1302. In the library CE pin of DS1302 is connected the IO5 of ESP32. But this pin is used for SPI communication (NSS pin). Is there possibility the change CE pin (use other GPIO )?

**Comment by Erriez** [comment]
Hi @saadsdz, Thanks for using my library. Yes, you can use any GPIO pin, because this library uses low-level bit-banging.  
See https://github.com/Erriez/ErriezDS1302/blob/0093bc7bd60a79021bfb5e8527ff903f05c27716/src/ErriezDS1302.h#L102

Does this answer your question?
